# Generated by Django 4.1.4 on 2023-03-01 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Annotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-creation_date"],
            },
        ),
        migrations.CreateModel(
            name="Emotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("emoji", models.CharField(max_length=250)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-creation_date", "name"],
            },
        ),
        migrations.CreateModel(
            name="Audio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=250)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                (
                    "annotation",
                    models.ManyToManyField(
                        through="notes.Annotation", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="music",
                        to="accounts.language",
                    ),
                ),
            ],
            options={
                "ordering": ["-creation_date", "number", "language"],
            },
        ),
        migrations.AddField(
            model_name="annotation",
            name="audio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annotations",
                to="notes.audio",
            ),
        ),
        migrations.AddField(
            model_name="annotation",
            name="emotion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="notes.emotion"
            ),
        ),
        migrations.AddField(
            model_name="annotation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="annotations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
