# Generated by Django 4.1.4 on 2023-04-06 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="audio",
            options={"ordering": ["-creation_date", "path", "language"]},
        ),
        migrations.RenameField(
            model_name="audio",
            old_name="number",
            new_name="path",
        ),
    ]
