# Generated by Django 4.1.4 on 2023-04-06 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0002_alter_user_language"),
        ("notes", "0002_alter_audio_options_rename_number_audio_path"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnnotationVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-creation_date"],
            },
        ),
        migrations.AddField(
            model_name="audio",
            name="number",
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=250)),
                ("path", models.CharField(max_length=250)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                (
                    "annotation",
                    models.ManyToManyField(
                        through="notes.AnnotationVideo", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="video",
                        to="accounts.language",
                    ),
                ),
            ],
            options={
                "ordering": ["-creation_date", "number", "path", "language"],
            },
        ),
        migrations.AddField(
            model_name="annotationvideo",
            name="Video",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annotations",
                to="notes.video",
            ),
        ),
        migrations.AddField(
            model_name="annotationvideo",
            name="emotion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="notes.emotion"
            ),
        ),
        migrations.AddField(
            model_name="annotationvideo",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="annotation_video",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
