# Generated by Django 4.1.4 on 2023-04-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0003_annotationvideo_audio_number_video_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="audio",
            name="numAnnotate",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="video",
            name="numAnnotate",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
