# Generated by Django 4.1.4 on 2023-04-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0005_alter_video_numannotate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audio",
            name="numAnnotate",
            field=models.IntegerField(default=0),
        ),
    ]
