# Generated by Django 4.1.4 on 2023-04-21 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0006_alter_audio_numannotate"),
    ]

    operations = [
        migrations.CreateModel(
            name="AudioResultAnnotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("audio_name", models.CharField(max_length=250)),
                ("note_name", models.CharField(max_length=250)),
                ("note_emoji", models.CharField(max_length=250)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                (
                    "audio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="note_finale",
                        to="notes.audio",
                    ),
                ),
            ],
            options={
                "ordering": ["-creation_date"],
            },
        ),
    ]
