# Generated by Django 4.1.4 on 2023-05-10 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0007_audioresultannotation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="video",
            options={"ordering": ["-creation_date", "name", "path", "language"]},
        ),
        migrations.RenameField(
            model_name="audio",
            old_name="number",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="video",
            old_name="number",
            new_name="name",
        ),
    ]
